#+html_head: <link rel="stylesheet" type="text/css" href="/home/ticks/Public/org_style.css" />
#+title: 红黑树

* 红黑树 
** 红黑树的介绍
红黑树是一种特殊的二叉搜索树, 每个节点多出了一个颜色属性,并满足一下 5 条性质
1. 每个节点或者是黑色，或者是红色
2. 根节点是黑色的
3. 空的叶子节点是黑色的
4. 红色节点的孩子是黑色的
5. 每个节点到叶子的路径包含相同的黑色节点
** 红黑树的性质
  *引理*
#+BEGIN_QUOTE
n 个内部节点的红黑树最大高度为 $2log_2(n+1)$
#+END_QUOTE
*证明*
#+BEGIN_PROOF
先证以 x 为根的子树最少有 $2^{bh(x)}-1$ 个内部节点. 

1. 当 x 为空的叶子节点时, 以 x 为根的子树有 $2^0-1=0$ 个内部节点, 满足.
2. 当 x 有两个内部孩子节点时, 孩子节点的黑色高度(black-height)为 bh(x) (/* 当 x 为红色节点*/)  或者为 bh(x) -1 (/* 当 x 为黑色节点  */)
3. 所以 x 的节点数目 $n\geqslant 2^{bh(x)-1}-1+2^{bh(x)-1}-1+1=2^{bh(x)}-1$
4. 又 $bh(x)\geqslant h/2$, 所以 $n\geqslant 2^{h/2}-1$
5. 所以 $h\leqslant 2log_2(n+1)$
#+END_PROOF

** 旋转

左旋
1. x 右孩子 y 的左孩子成为 x 的右孩子
2. x 成为 y 的左孩子
3. y 取代 x 的位置

右旋
1. x 左孩子 y 的右孩子成为 x 的左孩子
2. x 成为 y 的右孩子
3. y 取代 x 的位置

file:right.png
file:left.png
** 插入
1. 根据 key 值的大小插入新的节点 z, 颜色为红色
2. 若插入的是根节点, 只需要把根设为黑色
3. 若插入节点 z 的 parent 是红色的
   1. z 的 uncle 是红色的, 将 parent 和 uncle 设为黑色, grandparent 设为红色, 将 grandparent 当成插入节点, 重新判断
   2. z 的 uncle 是黑色的(tip. T.nil 也是黑色的), 将 z 到 uncle 的路径调为人形, parent 设为黑色 grandparent 设为红色, 将 grandparent 向 uncle 方向旋转
#+BEGIN_SRC C++
template <typename T>
void RBTree<T>::leftRoate(RBNode<T>* x)
{
	RBNode<T>* y = x->right;
	x->right     = y->left;
	if (x->right) x->right->parent = x;
	y->parent = x->parent;
	if (!y->parent)
		root = y;
	else if (y->parent->left == x)
		y->parent->left = y;
	else
		y->parent->right = y;
	y->left   = x;
	x->parent = y;
}

template <typename T>
void RBTree<T>::rightRoate(RBNode<T>* x)
{
	RBNode<T>* y = x->left;
	x->right     = y->left;
	if (y->left) y->left->parent = y;
	y->parent = x->parent;
	if (!y->parent)
		root = y;
	else if (y->parent->left == x)
		y->parent->left = y;
	else
		y->parent->right = y;
	y->right  = x;
	x->parent = y;
}

template <typename T>
void RBTree<T>::insert(T key)
{
	RBNode<T>* z  = new RBNode<T>(RED, key, nullptr, nullptr, nullptr);
	RBNode<T>* px = root;
	RBNode<T>* py = nullptr;
	while (root)
	{
		py = px;
		if (key < px->key)
			px = px->left;
		else
			px = px->right;
	}
	z->parent = py;
	if (!py)
		root = z;
	else if (z->key < py->key)
		py->left = z;
	else
		py->right = z;
	insertFix(z);
}

template <typename T>
void RBTree<T>::insertFix(RBNode<T>* z)
{
	while (z->parent && z->parent->color == RED)
	{
		if (z->parent == z->parent->parent->left)
		{
			RBNode<T>* uncle = z->parent->parent->right;
			if (uncle && uncle->color == RED)
			{
				uncle->color             = BLACK;
				z->parent->color         = BLACK;
				z->parent->parent->color = RED;
				z                        = z->parent->parent;
			}
			else if (z == z->parent->right)
			{
				z = z->parent;
				leftRoate(z);
			}
			z->parent->color         = BLACK;
			z->parent->parent->color = RED;
			rightRoate(z->parent->parent);
		}
		else
		{
			RBNode<T>* uncle = z->parent->parent->left;
			if (uncle && uncle->color == RED)
			{
				uncle->color             = BLACK;
				z->parent->color         = BLACK;
				z->parent->parent->color = RED;
				z                        = z->parent->parent;
			}
			else if (z == z->parent->left)
			{
				z = z->parent;
				rightRoate(z);
			}
			z->parent->color         = BLACK;
			z->parent->parent->color = RED;
			leftRoate(z->parent->parent);
		}
	}
	root->color = BLACK;
}

#+END_SRC

*** 没有父指针的红黑树插入
插入时需要回返节点来进行修正, 若不提供父指针就需要栈来保存插入时的路径
#+begin_example 
RB-INSERT(T, z)
    y = T.nil
    x = T.root
    stack St
    while x ≠ T.nil
        y = x
        if z.key < x.key
            x = x.left
        else
            x = x.right
        St.push(y)
    if y == T.nil
        T.root = z
    elseif z.key < y.key
        y.left = z
    else 
        y.right = z
    z.left = T.nil
    z.right = T.nil
    z.color = RED
    RB-INSERT-FIXUP(T, z, St)

RB-INSERT-FIXUP(T, z, St)
    while z ≠ T.root and (p = St.pop()).color == RED // pop 是 top, pop 2合1
        gp = St.pop()
        if p == gp.left
            uncle = gp.right
            if uncle.color == RED
                uncle.color = BLACK
                p.color = BLACK
                gp.color = RED
                z = gp
            else
                if z = p.right
                    leftRoate(T, p)
                    swap(z, p)
                p.color = BLACK
                gp.color = RED
                rightRoate(gp)
                break
        else (same as before clause with "left" and "right" exchanged)
    T.root.color = BLACK
#+end_example
** 删除   
*** 子树替换的辅助程序
#+BEGIN_SRC C++
  template <typename T>
  void RBTree<T>::transSubtree(RBNode<T>* src, RBNode<T>* dic)
  {
    if (!src->parent)
      root = dic;
    else if (src == src->parent->left)
      src->parent->left = dic;
    else
      src->parent->right = dic;
    if (dic) dic->parent = src->parent;
  }
#+END_SRC

*** 删除节点 z
1. z 的孩子小于 2 个. =y = z=, =x = z->child=
2. z 有 2 个孩子. 两个指针 x, y; y 指向 z 的后继. x 总是指向 y 的替代者 =x = y->right=. 保存 y 的原始颜色
 =y = successor(z)=, =x = y->right=
#+BEGIN_SRC C++
  template <typename T>
  void RBTree<T>::remove(RBNode<T>* z)
  {
    if (!z->left)
    {
      transSubtree(z, z->right);
    }
    else if (!z->right)
    {
      transSubtree(z, z->left);
    }
    else
    {
      RBNode<T>* y = successor(z);
      RBNode<T>* x = y->right;

      RBColor yOriginalCol = y->color;
      if (y->parent == z)
        x->parent = y;
      else
      {
        transSubtree(y, x);
        y->right         = z->right;
        y->right->parent = y;
      }
      transSubtree(z, y);
      y->left         = z->left;
      y->left->parent = y;
      delete z;
      if (yOriginalCol == BLACK) removeFix(x);
    }
  }
#+END_SRC

*** 修复红黑树, 使其满足 5 条性质
**** y 的原始颜色是红色的, 则红黑树的性质仍然保持
1. 树中黑高不变, 保持性质 5
2. y 在新位置的颜色是 z 的颜色所以新位置, y 不会破坏性置 4. 若 y 是红色的, 则 x 是黑色的, x 替代 y 也不会破坏性置 4
3. 明显根结点的颜色不会变, 所有结点没有多出或少颜色, 空叶子节点的颜色也不会变化. 所以性质 1,2,3 保持
**** y 是黑色的, 给 x 添加一个黑色
1. 有可能产生的问题
  | 编号 |                 问题                  |                              解决办法 |
  |------+---------------------------------------+---------------------------------------|
  | <l>  |                  <c>                  |                                   <r> |
  | 1    |       若 x 是根,违返了性质 1, 2       | 只保留 x 的一个黑色 =x.color = BLACK= |
  | 2    |     若 x 是红黑色的违返性质 1         |       去除 x 的红色 =x.color = BLACK= |
  | 3    | 若 x 不是根且是双黑色的, 违返了性质 1 |                                  [[solver 1][办法]] |
   
2. 解决办法 <<solver 1>>
   1. *x 的兄弟节点 brother 是红色的*. 
      
         =x.parent.colr = RED, brother.color=BLACK= 向 x 方向旋转 =x.parent=
   2. *x 的兄弟节点 brother 是黑色的*
      * *brother 的孩子都是是黑色的*
          #+BEGIN_SRC C
          brother.color = RED;
          x = x.parent;
          #+END_SRC
      * *=brother.left.color = RED=, =brother.right.color = BLACK=*
      * *=brother.right.colr =RED=*
 
